title: Site

pages:
  template:
    - default
    - contact
    - archive

fields:
  title:
    label: Title
    type:  text
    width: 2/3

  color:
    label: Theme color
    type: color
    default: '#ff706c'
    width: 1/3

  tagline:
    label: Tagline
    type:  text
    required: true
    width: 2/3

  logo:
    label: Header image
    type: quickselect
    options: images
    width: 1/3

  description:
    label: Description
    type:  textarea

  categories:
    label: Site-wide categories
    type: tags

  no_posts:
    label: No posts
    type: textarea
    help: >
      This message is displayed when no (visible) posts are available.

  error:
    label: Search error
    type: textarea
    help: >
      This message is displayed when no search results could be found,
      followed by a search form.



  footer:
    label: Footer text
    type:  textarea
